[project]
name = "bagel"
version = "0.1.0"
description = "Scripts for ingesting data & producing MARC21 records for BPL Board Game Library"
authors = [
    {name = "Tomasz Kalata",email = "klingaroo@gmail.com"},
    {name = "Charlotte Kostelic",email = "charlottekostelic@bookops.org"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pymarc (>=5.3)", "pandas (>=3.0)", "pandas-stubs (>=2.2.3.241126)",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = '--cov=bagel/'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
branch = true
relative_files = true
source = ["."]

[tool.ruff.lint]
select = ["F", "E", "ANN"]
ignore = ["ANN401"]

[tool.ruff.format]
skip-magic-trailing-comma = true
